under the following directory:

YOUR_GITHUB_USERNAME --> .github --> workflows --> FILE_NAME.yml


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: anirAchibane
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Step 3. Running GitHub Actions
Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green ‚úÖ "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" ‚úÖ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput

Step 4. Adding a contribution-eating snake to your profile
Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

SnakeEating

Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?

GitHub Like a Boss (25 Part Series)
1
GitHub Desktop for better repo organisation
2
GitHub README for easy to understand code
...
21 more parts...
24
GitHub Issues or GitHub Discussions? What's the difference, and when should you use each one?
25
GitHub Copilot - Methods, modes, and Models: Which one is the best?
profile
Postmark
Promoted

Postmark Image

20% off for developers who'd rather build features than debug email
Stop wrestling with email delivery and get back to the code you love. Postmark handles the complexities of email infrastructure so you can ship your product faster.

Start free

Read More
Top comments (50)
Subscribe
pic
Add to the discussion
 
 
platane profile image
Platane
‚Ä¢
21 Aug 24 ‚Ä¢ Edited

Hi, First of all thanks for the precise tutorial!

There were a few changes in the action (mostly to adapt to github api), I had to change some parameters and bump the version.

Unfortunately a lot of people use the edge version ( with the tag #master ). It's a bit of a mess but the result is that this version is deprecated and can no longer work without adding some modification from the user (adding a github token as param)

The recommended usage is now this declaration:

- uses: Platane/snk/svg-only@v3
  with:
    github_user_name: ${{ github.repository_owner }}
    outputs: |
      dist/github-snake.svg
Check the readme for details about the new options


4
Like

 
 
arorasir profile image
Mohit Arora
‚Ä¢
24 Sept 24

Finally something worked :D


3
Like

 
 
mishmanners profile image
Michelle Duke
‚Ä¢
25 Sept 24

Thanks for putting this together ‚ù§Ô∏è


2
Like

 
 
1seamy profile image
seamy
‚Ä¢
8 Apr 24 ‚Ä¢ Edited

Thanks Michelle Mannering for your (dev.to/mishmanners/how-to-enable-g...) topic.

If other users wish to utilize this, kindly modify this topic;

1-Use this (thanks Platane github.com/Platane) file;

github.com/1SeaMy/1SeaMy/blob/main...

2-Use this;

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake-dark.svg)

or this

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.svg)


4
Like

 
 
kushaltanna24 profile image
KushalTanna24
‚Ä¢
3 Jun 22

Work fine.! Here is mine - KushalTanna24


2
Like

 
 
msoftware profile image
Michael jentsch
‚Ä¢
9 Jul 21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
Like

 
 
gustavohgmartins profile image
Gustavo Martins
‚Ä¢
3 Sept 21

Awsome! How did you change the background-color?


Like

 
 
mishmanners profile image
Michelle Duke
‚Ä¢
3 Sept 21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
Like
Thread
 
gustavohgmartins profile image
Gustavo Martins
‚Ä¢
3 Sept 21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voil√°


2
Like
Thread
 
mishmanners profile image
Michelle Duke
‚Ä¢
3 Sept 21

Awesome! Glad to be of help üòÑ


1
Like

 
 
jakon62508112 profile image
Jakob
‚Ä¢
20 Jan 23 ‚Ä¢ Edited

Getting this error when I try to run workflow and after it fails:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.


1
Like

 
 
shuvajitgeek profile image
Shuvajit
‚Ä¢
1 Feb 23

go to setting -> action -> and check the workflow as read and write
(run build again) hopefully you will not get error


Like

 
 
l3on06 profile image
L3on06
‚Ä¢
17 Feb 23

Hello everyone, before proceeding, please navigate to 'Settings -> Actions -> General -> Workflow Permissions' in your README.md file and select 'Read and Write' permissions. This is important because if you have other permissions selected, it may result in errors.


2
Like

 
 
unknow0074 profile image
Unknown
‚Ä¢
27 May 24

I specially created account to say thank you I almost wasted my 3 hours in wandering around to fix issue and you saved my life.** Thank you**


Like

 
 
baayah profile image
BAayah
‚Ä¢
11 Jan 24

Thank you so much! I tried to change in settings 'Contribution' to 'include my private contributions' but anyway my Readme profile doesn't show My Contributions. Could you please help me with this?
github.com/BAayah/BAayah


Like

 
 
ariafatah profile image
Ariafatah
‚Ä¢
18 Sept 23

github.com/ariafatah0711/ariafatah...

Check my github and change this file because I tried the file above only as much as it appears if you want to use the full one I use. And don't forget to give starsüòÅ


1
Like

 
 
ariafatah profile image
Ariafatah
‚Ä¢
18 Sept 23

If the action fails, you can go to repo settings, click action, then select general, and look at the bottom where it says read and write.


1
Like

 
 
hoangtien_2k3 profile image
Ho√†ng Anh Ti·∫øn
‚Ä¢
29 Jan 23 ‚Ä¢ Edited

It does not work for me. Can someone help me?
github.com/hoangtien2k3qx1

Error:
actions/checkout@v2, platane/snk@master, ad-m/github-push-action@master, and crazy-max/ghaction-github-pages@v2.1.3 are not allowed to be used in hoangtien2k3qx1/hoangtien2k3qx1. Actions in this workflow must be: within a repository owned by hoangtien2k3qx1.


1
Like

 
 
bpolaswar profile image
Bhumesh Polaswar
‚Ä¢
17 Oct 21

Great worked for me. See github.com/bpolaswar
Thanks.


2
Like

View full discussion (50 comments)
Code of Conduct ‚Ä¢ Report abuse
profile
Postmark
Promoted

Postmark Image

"Please fix this..."
Focus on creating stellar experiences without email headaches. Postmark's reliable API and detailed analytics make your transactional emails as polished as your product.

Start free


Michelle Duke
Follow
Senior Developer Advocate | Hackathon Queen | International Speaker
Location
Australia
Education
The University of Melbourne
Joined
29 May 2020
More from Michelle Duke
GitHub Copilot - Methods, modes, and Models: Which one is the best?
#github #githubcopilot #ai #tutorial
GitHub Issues or GitHub Discussions? What's the difference, and when should you use each one?
#github #tutorial #community
Best community tech Discord servers to join
#discord #community #opensource
profile
DevCycleHQ
Promoted

DevCycle image

Ship Faster, Stay Flexible.
DevCycle is the first feature flag platform with OpenFeature built-in to every open source SDK, designed to help developers ship faster while avoiding vendor-lock in.

Start shipping


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
